baseURL = 'https://sametk0ca.github.io/'
defaultContentLanguage = 'en'
title = 'Samet Koca | Cyber Security'
theme = 'papermod'

[languages]
  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    weight = 1
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Posts"
        url = "posts/"
        weight = 10
      [[languages.en.menu.main]]
        name = "KB"
        url = "kb/"
        weight = 20

  [languages.tr]
    languageCode = "tr-tr"
    languageName = "Türkçe"
    weight = 2
    [languages.tr.menu]
      [[languages.tr.menu.main]]
        name = "Yazılar"
        url = "posts/"
        weight = 10

[params]
  ShowToc = true
  defaultTheme = "dark"
  description = "Cyber Security Blog, Wiki & Technical Research"
  author = "Samet Koca"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  
  # Technical Rendering
  math = true # Enable KaTeX
  mermaid = true # Enable Mermaid.js

  [params.profileMode]
    enabled = true
    title = "Samet Koca"
    subtitle = "Security Researcher | CyBOK Wiki Architect"
    imageUrl = "/avatar.jpg"
    imageWidth = 120
    imageHeight = 120

  [params.toc]
    enable = true
    autoCollapse = false
    ordered = false

  [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/sametk0ca"

  [[params.socialIcons]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/samet-koca-7b3033188/"

  [[params.socialIcons]]
    name = "Email"
    url = "mailto:samet.kocats@gmail.com"

[menu]
  [[menu.main]]
    identifier = "writeups"
    name = "Writeups"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "Whoami"
    url = "/about/"
    weight = 50

[markup.highlight]
  noClasses = false
  style = "dracula"
  tabWidth = 4
  lineNos = true
  guessSyntax = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
